### PR TITLE
Fixed chinese fonts display problem , see #138

### PR DESCRIPTION
**Pull request by cnmade**
The microsoft YaHei will be available for win7 + , so please add it

### CODE REVIEW

**Comment by netroby** [comment]
**https://www.microsoft.com/typography/fonts/family.aspx?FID=350**

**Comment by netroby** [comment]
ping @rahmanusta

**Comment by rahmanusta** [comment]
Dear @netroby. Can it be a drawback for non-chinese users ?

**Comment by netroby** [comment]
If the fonts missing, then it will pick fonts by the order of the fonts define list.

**Comment by netroby** [comment]
@rahmanusta Dear sir , add more common chinese fonts .

Now tested under windows, linux, osx.

FYI, i am using English environment (archlinux) , and installed wqy microhei fonts.

Working correct.

[readme.pdf](https://github.com/asciidocfx/AsciidocFX/files/1219363/readme.pdf)

**Comment by michoule** [comment]
@netroby 大神，中文如何支持？

**Comment by netroby** [comment]
It works, as i described. Seems this project dead(no longer maintained.)

**Comment by life888888** [comment]
我寫了可以支援  AsciidocFX 1.7.6+ 產生包含中文字元PDF的小東西
I wrote something can support AsciidocFX create Chinese Character PDF

https://github.com/life888888/asciidoctor-pdf-cjk-ext#asciidocfx

只需要下載, 設定 , 就可以使用
1 下載 https://github.com/life888888/asciidoctor-pdf-cjk-ext/releases/download/v0.1.0/pdf-ext-notosans-cjk-sc.jar
到 AsciidocFX/lib 目錄下

2 設定
`AsciidocFX/conf/asciidoctor_pdf.json` 或 `~/.AsciidocFX-1.8.0/asciidoctor_pdf.json`
```json
{
	"backend": "pdf",
	"jsPlatform":"Asciidoctorj",
	"safe": "unsafe",
	"header_footer": true,
	"converter": "ASCIIDOCTOR",
	"attributes": {
                "pdf-fontsdir": "uri:classloader:/data/fonts;GEM_FONTS_DIR;",
                "pdf-themesdir": "uri:classloader:/data/themes",
                "pdf-theme": "default-ext-notosans-cjk-tc",	
		"showtitle": "true",
		"allow-uri-read": "true",
		"source-highlighter": "rouge",
		"icons": "font",
		"imagesdir": "images",
		"experimental": "true"
	}
}
```
3 就可以使用

它支援三種字型 
Noto Sans CJK, Noto Sans Mono CJK, Noto Serif CJK

每種字型包含四種樣式
4 Style Regular, Bold, Italic , Bold Italic

如果你要產生自己使用字型的四種樣式(前提是要有`一般`跟`粗體`)，可以參考以下專案
if you want to create your font can reference:  https://github.com/life888888/cjk-fonts-ttf

如果你要產生自己的 asciidoctor 字型跟 theme 可以參考以下專案 (AsciidocFX 使用 ASCIIDOCTOR 去轉 PDF)
if you want to create your asciidoctor font and theme can reference https://github.com/life888888/asciidoctor-pdf-cjk-ext

**Pull request closed without merging**
